namespace Stay.Core;

/// <summary>
/// Bundled apps this app knows by name. The list is adapted from Raphire/Win11Debloat (MIT) with the wording
/// changed, and came here from Quiet for Windows whole.
///
/// Removing one is the only thing this app does that a receipt cannot undo, so the receipt keeps the Store link
/// for putting it back and the window says so before anything is removed.
/// </summary>
public static class Apps
{
    public static readonly IReadOnlyList<AppEntry> Known = new AppEntry[]
    {
        new("Clipchamp.Clipchamp", "Clipchamp", "Video editor from Microsoft.", AppAdvice.Junk),
        new("Microsoft.3DBuilder", "3D Builder", "Basic 3D modeling software.", AppAdvice.Junk),
        new("Microsoft.549981C3F5F10", "Cortana", "Microsoft Cortana voice assistant (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingFinance", "Bing Finance", "Finance news and tracking (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingFoodAndDrink", "Bing Food And Drink", "Recipes and food news (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingHealthAndFitness", "Bing Health And Fitness", "Health and fitness tracking/news (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingNews", "Bing News", "News aggregator (Replaced by Microsoft News/Start).", AppAdvice.Junk),
        new("Microsoft.BingSports", "Bing Sports", "Sports news and scores (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingTranslator", "Bing Translator", "Translation service.", AppAdvice.Junk),
        new("Microsoft.BingTravel", "Bing Travel", "Travel planning and news (discontinued).", AppAdvice.Junk),
        new("Microsoft.BingWeather", "Bing Weather", "Weather forecast.", AppAdvice.Junk),
        new("Microsoft.Windows.AIHub", "Copilot+ AI Hub", "Copilot+ AI Hub app (Windows 11 24H2+).", AppAdvice.Junk),
        new("Microsoft.PCManager", "Microsoft PC Manager", "Microsoft PC Manager system cleanup and optimization tool (often preinstalled).", AppAdvice.Junk),
        new("Microsoft.Getstarted", "Get Started", "Tips and introductory guide for Windows (Cannot be uninstalled in Windows 11).", AppAdvice.Junk),
        new("Microsoft.Messaging", "Messaging", "Messaging app, often integrates with Skype (Largely discontinued).", AppAdvice.Junk),
        new("Microsoft.Microsoft3DViewer", "3D Viewer", "Viewer for 3D models.", AppAdvice.Junk),
        new("Microsoft.MicrosoftJournal", "Microsoft Journal", "Digital note-taking app optimized for pen input.", AppAdvice.Junk),
        new("Microsoft.MicrosoftOfficeHub", "Office Hub", "Hub to access Microsoft Office apps and documents (Precursor to Microsoft 365 app).", AppAdvice.Junk),
        new("Microsoft.MicrosoftPowerBIForWindows", "Power BI", "Business analytics service client.", AppAdvice.Junk),
        new("Microsoft.MicrosoftSolitaireCollection", "Solitaire Collection", "Collection of solitaire card games.", AppAdvice.Junk),
        new("Microsoft.MicrosoftStickyNotes", "Sticky Notes", "Digital sticky notes app (Discontinued & replaced by OneNote).", AppAdvice.Junk),
        new("Microsoft.MixedReality.Portal", "Mixed Reality Portal", "Portal for Windows Mixed Reality headsets.", AppAdvice.Junk),
        new("Microsoft.NetworkSpeedTest", "Network Speed Test", "Internet connection speed test utility.", AppAdvice.Junk),
        new("Microsoft.News", "Microsoft News", "News aggregator (Replaced Bing News, now part of Microsoft Start).", AppAdvice.Junk),
        new("Microsoft.Office.OneNote", "OneNote", "Digital note-taking app.", AppAdvice.Junk),
        new("Microsoft.Office.Sway", "Sway", "Presentation and storytelling app.", AppAdvice.Junk),
        new("Microsoft.OneConnect", "One Connect", "Mobile Operator management app (Replaced by Mobile Plans).", AppAdvice.Junk),
        new("Microsoft.Print3D", "Print 3D", "3D printing preparation software.", AppAdvice.Junk),
        new("Microsoft.PowerAutomateDesktop", "Power Automate", "Desktop automation tool (RPA).", AppAdvice.Junk),
        new("Microsoft.SkypeApp", "Skype (UWP)", "Skype communication app, Universal Windows Platform version (discontinued).", AppAdvice.Junk),
        new("Microsoft.Todos", "Microsoft To Do", "To-do list and task management app.", AppAdvice.Junk),
        new("Microsoft.Windows.DevHome", "Dev Home", "Developer dashboard and tool configuration utility (discontinued).", AppAdvice.Junk),
        new("Microsoft.WindowsAlarms", "Alarms & Clock", "Alarms & Clock app.", AppAdvice.Junk),
        new("Microsoft.WindowsFeedbackHub", "Feedback Hub", "App for providing feedback to Microsoft on Windows.", AppAdvice.Junk),
        new("Microsoft.WindowsMaps", "Windows Maps", "Mapping and navigation app.", AppAdvice.Junk),
        new("Microsoft.WindowsSoundRecorder", "Sound Recorder", "Basic audio recording app.", AppAdvice.Junk),
        new("Microsoft.XboxApp", "Xbox Console Companion", "Old Xbox Console Companion App (discontinued).", AppAdvice.Junk),
        new("Microsoft.ZuneVideo", "Movies & TV", "Movies & TV app for renting/buying/playing video content (Rebranded as \"Films & TV\").", AppAdvice.Junk),
        new("MicrosoftCorporationII.MicrosoftFamily", "Family Safety", "Family Safety App for managing family accounts and settings.", AppAdvice.Junk),
        new("MicrosoftCorporationII.QuickAssist", "Quick Assist", "Remote assistance tool.", AppAdvice.Junk),
        new("MicrosoftTeams", "Microsoft Teams (Old)", "Old Microsoft Teams personal (Store version).", AppAdvice.Junk),
        new("MSTeams", "Microsoft Teams (New)", "New Microsoft Teams app (Work/School or Personal).", AppAdvice.Junk),
        new("ACGMediaPlayer", "ACG Media Player", "Media player app.", AppAdvice.Junk),
        new("ActiproSoftwareLLC", "Actipro Software", "Possibly UI controls or software components, often bundled by PC makers.", AppAdvice.Junk),
        new("AdobeSystemsIncorporated.AdobePhotoshopExpress", "Adobe Photoshop Express", "Basic photo editing app from Adobe.", AppAdvice.Junk),
        new("Amazon.com.Amazon", "Amazon", "Amazon shopping app.", AppAdvice.Junk),
        new("AmazonVideo.PrimeVideo", "Prime Video", "Amazon Prime Video streaming service app.", AppAdvice.Junk),
        new("Asphalt8Airborne", "Asphalt 8", "Racing game.", AppAdvice.Junk),
        new("AutodeskSketchBook", "Autodesk SketchBook", "Digital drawing and sketching app.", AppAdvice.Junk),
        new("CaesarsSlotsFreeCasino", "Caesars Slots", "Casino slot machine game.", AppAdvice.Junk),
        new("COOKINGFEVER", "Cooking Fever", "Restaurant simulation game.", AppAdvice.Junk),
        new("CyberLinkMediaSuiteEssentials", "CyberLink Media Suite", "Multimedia software suite (often preinstalled by PC makers).", AppAdvice.Junk),
        new("DisneyMagicKingdoms", "Disney Magic Kingdoms", "Disney theme park building game.", AppAdvice.Junk),
        new("Disney.37853FC22B2CE", "Disney+", "Disney+ streaming service app.", AppAdvice.Junk),
        new("DrawboardPDF", "Drawboard PDF", "PDF viewing and annotation app, often focused on pen input.", AppAdvice.Junk),
        new("Duolingo-LearnLanguagesforFree", "Duolingo", "Language learning app.", AppAdvice.Junk),
        new("EclipseManager", "Eclipse Manager", "Often related to specific maker's software or utilities (e.g. for managing screen settings).", AppAdvice.Junk),
        new("FACEBOOK.FACEBOOK", "Facebook", "Facebook social media app.", AppAdvice.Junk),
        new("FarmVille2CountryEscape", "FarmVille 2", "Farming simulation game.", AppAdvice.Junk),
        new("Flipboard", "Flipboard", "News and social network aggregator styled as a magazine.", AppAdvice.Junk),
        new("HiddenCity", "Hidden City", "Hidden object puzzle adventure game.", AppAdvice.Junk),
        new("HULULLC.HULUPLUS", "Hulu", "Hulu streaming service app.", AppAdvice.Junk),
        new("iHeartRadio", "iHeartRadio", "Internet radio streaming app.", AppAdvice.Junk),
        new("Facebook.Instagram", "Instagram", "Instagram social media app.", AppAdvice.Junk),
        new("king.com.BubbleWitch3Saga", "Bubble Witch 3", "Puzzle game from King.", AppAdvice.Junk),
        new("king.com.CandyCrushSaga", "Candy Crush Saga", "Puzzle game from King.", AppAdvice.Junk),
        new("king.com.CandyCrushSodaSaga", "Candy Crush Soda", "Puzzle game from King.", AppAdvice.Junk),
        new("LinkedInforWindows", "LinkedIn", "LinkedIn professional networking app.", AppAdvice.Junk),
        new("MarchofEmpires", "March of Empires", "Strategy game.", AppAdvice.Junk),
        new("4DF9E0F8.Netflix", "Netflix", "Netflix streaming service app.", AppAdvice.Junk),
        new("NYTCrossword", "NYT Crossword", "New York Times crossword puzzle app.", AppAdvice.Junk),
        new("OneCalendar", "One Calendar", "Calendar aggregation app.", AppAdvice.Junk),
        new("PandoraMediaInc", "Pandora", "Pandora music streaming app.", AppAdvice.Junk),
        new("PhototasticCollage", "Phototastic Collage", "Photo collage creation app.", AppAdvice.Junk),
        new("PicsArt-PhotoStudio", "PicsArt", "Photo editing and creative app.", AppAdvice.Junk),
        new("PolarrPhotoEditorAcademicEdition", "Polarr Photo Editor", "Photo editing app (Academic Edition).", AppAdvice.Junk),
        new("flaregamesGmbH.RoyalRevolt", "Royal Revolt", "Tower defense / strategy game.", AppAdvice.Junk),
        new("Sidia.LiveWallpaper", "Live Wallpaper", "Live wallpaper app.", AppAdvice.Junk),
        new("SlingTV", "Sling TV", "Live TV streaming service app.", AppAdvice.Junk),
        new("SpotifyAB.SpotifyMusic", "Spotify", "Spotify music streaming app.", AppAdvice.Junk),
        new("BytedancePte.Ltd.TikTok", "TikTok", "TikTok short-form video app.", AppAdvice.Junk),
        new("TuneInRadio", "TuneIn Radio", "Internet radio streaming app.", AppAdvice.Junk),
        new("WinZipUniversal", "WinZip", "File compression and extraction utility.", AppAdvice.Junk),
        new("Microsoft.BingSearch", "Bing Search", "Web Search from Microsoft Bing (Integrates into Windows Search).", AppAdvice.Optional),
        new("Microsoft.GamingApp", "Xbox Gaming App", "Modern Xbox Gaming App, required for installing some PC games.", AppAdvice.Optional),
        new("Microsoft.GetHelp", "Get Help", "Required for some Windows 11 Troubleshooters and support interactions.", AppAdvice.Keep),
        new("Microsoft.M365Companions", "Microsoft 365 Companions", "Microsoft 365 (Business) Calendar, Files and People mini-apps, these apps may be reinstalled if enabled by your Microsoft 365 admin.", AppAdvice.Optional),
        new("Microsoft.MSPaint", "Paint 3D", "Paint 3D (Modern paint application with 3D features).", AppAdvice.Optional),
        new("Microsoft.OutlookForWindows", "Outlook for Windows", "New Outlook for Windows mail client.", AppAdvice.Optional),
        new("Microsoft.Paint", "Paint", "Classic Paint (Traditional 2D paint application).", AppAdvice.Optional),
        new("Microsoft.People", "People", "Required for & included with Mail & Calendar (discontinued).", AppAdvice.Optional),
        new("Microsoft.RemoteDesktop", "Remote Desktop", "Remote Desktop client app.", AppAdvice.Optional),
        new("Microsoft.ScreenSketch", "Snipping Tool", "Snipping Tool (Screenshot and annotation tool).", AppAdvice.Optional),
        new("Microsoft.StartExperiencesApp", "Widgets feed", "The news feed inside the Widgets board.", AppAdvice.Junk),
        new("Microsoft.Whiteboard", "Whiteboard", "Digital collaborative whiteboard app.", AppAdvice.Optional),
        new("Microsoft.Windows.Photos", "Photos", "Default photo viewing and basic editing app.", AppAdvice.Optional),
        new("Microsoft.WindowsCalculator", "Calculator", "Calculator app.", AppAdvice.Optional),
        new("Microsoft.WindowsCamera", "Camera", "Camera app for using built-in or connected cameras.", AppAdvice.Optional),
        new("Microsoft.windowscommunicationsapps", "Mail & Calendar", "Mail & Calendar app suite (discontinued).", AppAdvice.Optional),
        new("Microsoft.WindowsNotepad", "Notepad", "Notepad text editor app.", AppAdvice.Optional),
        new("Microsoft.WindowsStore", "Microsoft Store", "Microsoft Store. Warning: This app cannot be reinstalled easily if removed.", AppAdvice.Keep),
        new("Microsoft.WindowsTerminal", "Windows Terminal", "Default terminal app in windows 11 (Command Prompt, PowerShell, WSL). Warning: it is the terminal this app's command line runs in.", AppAdvice.Keep),
        new("Microsoft.Xbox.TCUI", "Xbox TCUI Framework", "UI framework, seems to be required for Microsoft Store, photos and certain games.", AppAdvice.Keep),
        new("Microsoft.XboxGameOverlay", "Xbox Game Overlay", "Game overlay, required/useful for some games (Part of Xbox Game Bar).", AppAdvice.Optional),
        new("Microsoft.XboxGamingOverlay", "Xbox Gaming Overlay", "Game overlay, required/useful for some games (Part of Xbox Game Bar).", AppAdvice.Optional),
        new("Microsoft.XboxIdentityProvider", "Xbox Identity Provider", "Xbox sign-in framework, required for some games and Xbox services.", AppAdvice.Keep),
        new("Microsoft.XboxSpeechToTextOverlay", "Xbox Speech To Text", "Accessibility feature required for some games. Warning: This app cannot be reinstalled easily.", AppAdvice.Keep),
        new("Microsoft.YourPhone", "Phone Link", "Phone link (Connects Android/iOS phone to PC).", AppAdvice.Optional),
        new("Microsoft.ZuneMusic", "Media Player", "Modern Media Player (Replaced Groove Music, plays local audio/video).", AppAdvice.Optional),
        new("MicrosoftWindows.CrossDevice", "Cross Device Experience", "Phone integration within File Explorer, Camera and more (Part of Phone Link features).", AppAdvice.Optional),
        new("MicrosoftWindows.Client.WebExperience", "Widgets board (Web Experience Pack)", "The Widgets board itself, delivered through the Store. Removing it is how the board goes for good.", AppAdvice.Junk),
        new("Microsoft.WidgetsPlatformRuntime", "Widgets runtime", "What the Widgets board runs on. Nothing else uses it.", AppAdvice.Junk),
        new("LGElectronics.LGMonitorApp", "LG Monitor App", "LG maker's software for controlling your LG monitor, Windows Update may silently reinstall this app if you have an LG monitor connected.", AppAdvice.Optional),
        new("AD2F1837.HPAIExperienceCenter", "HP AI Experience Center", "HP maker's software, AI-enhanced features and support.", AppAdvice.Optional),
        new("AD2F1837.HPConnectedMusic", "HP Connected Music", "HP maker's software for music (possibly discontinued).", AppAdvice.Optional),
        new("AD2F1837.HPConnectedPhotopoweredbySnapfish", "HP Connected Photo", "HP maker's software for photos, integrated with Snapfish (possibly discontinued).", AppAdvice.Optional),
        new("AD2F1837.HPDesktopSupportUtilities", "HP Desktop Support Utilities", "HP maker's software providing desktop support tools.", AppAdvice.Optional),
        new("AD2F1837.HPEasyClean", "HP Easy Clean", "HP maker's software for system cleaning or optimization.", AppAdvice.Optional),
        new("AD2F1837.HPFileViewer", "HP File Viewer", "HP maker's software for viewing specific file types.", AppAdvice.Optional),
        new("AD2F1837.HPJumpStarts", "HP JumpStarts", "HP maker's software for tutorials, app discovery, or quick access to HP features.", AppAdvice.Optional),
        new("AD2F1837.HPPCHardwareDiagnosticsWindows", "HP PC Hardware Diagnostics", "HP maker's software for PC hardware diagnostics.", AppAdvice.Optional),
        new("AD2F1837.HPPowerManager", "HP Power Manager", "HP maker's software for managing power settings and battery.", AppAdvice.Optional),
        new("AD2F1837.HPPrinterControl", "HP Printer Control", "HP maker's software for managing HP printers.", AppAdvice.Optional),
        new("AD2F1837.HPPrivacySettings", "HP Privacy Settings", "HP maker's software for managing privacy settings.", AppAdvice.Optional),
        new("AD2F1837.HPQuickDrop", "HP QuickDrop", "HP maker's software for quick file transfer between devices.", AppAdvice.Optional),
        new("AD2F1837.HPQuickTouch", "HP QuickTouch", "HP maker's software, possibly for touch-specific shortcuts or controls.", AppAdvice.Optional),
        new("AD2F1837.HPRegistration", "HP Registration", "HP maker's software for product registration.", AppAdvice.Optional),
        new("AD2F1837.HPSupportAssistant", "HP Support Assistant", "HP maker's software for support, updates, and troubleshooting.", AppAdvice.Optional),
        new("AD2F1837.HPSureShieldAI", "HP Sure Shield AI", "HP maker's security software, likely AI-based threat protection.", AppAdvice.Optional),
        new("AD2F1837.HPSystemInformation", "HP System Information", "HP maker's software for displaying system information.", AppAdvice.Optional),
        new("AD2F1837.HPWelcome", "HP Welcome", "HP maker's software providing a welcome experience or initial setup help.", AppAdvice.Optional),
        new("AD2F1837.HPWorkWell", "HP WorkWell", "HP maker's software focused on well-being, possibly with break reminders or ergonomic tips.", AppAdvice.Optional),
        new("AD2F1837.myHP", "myHP", "HP maker's central hub app for device info, support, and services.", AppAdvice.Optional),
        new("E046963F.LenovoCompanion", "Lenovo Vantage", "Lenovo maker's hub app for device settings, updates, and support.", AppAdvice.Optional),
        new("LenovoCompanyLimited.LenovoVantageService", "Lenovo Vantage Service", "Background service component for Lenovo Vantage.", AppAdvice.Optional),
        new("DellInc.DellSupportAssistforPCs", "Dell SupportAssist", "Dell maker's support, diagnostic, and update tool.", AppAdvice.Optional),
        new("DellInc.DellDigitalDelivery", "Dell Digital Delivery Services", "Dell maker's software for delivering pre-purchased software.", AppAdvice.Optional),
        new("DellInc.DellMobileConnect", "Dell Mobile Connect", "Dell maker's app for linking Android/iOS phone to PC (superseded by Phone Link).", AppAdvice.Optional),
        new("Microsoft.Copilot", "Copilot app", "The Copilot app Microsoft installs alongside Windows.", AppAdvice.Junk),
        new("Microsoft.Windows.Ai.Copilot.Provider", "Copilot provider", "Helper package for Copilot.", AppAdvice.Junk),
        new("MicrosoftWindows.Client.CoPilot", "Copilot (system)", "Windows' built-in Copilot component.", AppAdvice.Junk),
        // Pieces Windows itself relies on that show up as ordinary packages. Offered as "keep" so nobody wonders what they are.
        new("Microsoft.AV1VideoExtension", "AV1 Video Extension", "Codec Windows uses to play AV1 video. Removing it breaks playback in Photos, Edge and the Media Player.", AppAdvice.Keep),
        new("Microsoft.AVCEncoderVideoExtension", "AVC Encoder Video Extension", "Codec Windows uses to record H.264 video.", AppAdvice.Keep),
        new("Microsoft.HEIFImageExtension", "HEIF Image Extension", "Codec Windows uses to open HEIF and HEIC photos, the kind iPhones take.", AppAdvice.Keep),
        new("Microsoft.HEVCVideoExtension", "HEVC Video Extension", "Codec Windows uses to play H.265 video.", AppAdvice.Keep),
        new("Microsoft.HEVCVideoExtensions", "HEVC Video Extensions", "Codec Windows uses to play H.265 video.", AppAdvice.Keep),
        new("Microsoft.MPEG2VideoExtension", "MPEG-2 Video Extension", "Codec Windows uses to play MPEG-2 video and DVDs.", AppAdvice.Keep),
        new("Microsoft.RawImageExtension", "Raw Image Extension", "Codec Windows uses to open camera raw photos.", AppAdvice.Keep),
        new("Microsoft.VP9VideoExtensions", "VP9 Video Extensions", "Codec Windows uses to play VP9 video, common on the web.", AppAdvice.Keep),
        new("Microsoft.WebMediaExtensions", "Web Media Extensions", "Codecs Windows uses to play Ogg, Vorbis and Theora media.", AppAdvice.Keep),
        new("Microsoft.WebpImageExtension", "WebP Image Extension", "Codec Windows uses to open WebP pictures.", AppAdvice.Keep),
        new("Microsoft.Winget.Source", "Windows Package Manager source", "The list of apps winget can install. winget stops working without it.", AppAdvice.Keep),
        new("Microsoft.ApplicationCompatibilityEnhancements", "Application Compatibility Enhancements", "Fixes Windows applies so older programs keep running.", AppAdvice.Keep),
    };

    /// <summary>Package names the app never offers to remove: Windows would not work without them.</summary>
    public static readonly IReadOnlySet<string> Untouchable = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "Microsoft.WindowsStore", "Microsoft.StorePurchaseApp", "Microsoft.DesktopAppInstaller", "Microsoft.WindowsTerminal",
        "Microsoft.SecHealthUI", "Microsoft.Windows.ShellExperienceHost", "Microsoft.Windows.StartMenuExperienceHost",
        "Microsoft.Windows.Search", "Microsoft.AAD.BrokerPlugin", "Microsoft.AccountsControl", "Microsoft.LockApp",
        "Microsoft.Windows.CloudExperienceHost", "Microsoft.Windows.ContentDeliveryManager", "Microsoft.Win32WebViewHost",
        "Microsoft.MicrosoftEdge.Stable", "Microsoft.UI.Xaml.CBS", "Microsoft.WindowsAppRuntime.CBS", "Microsoft.XboxGameCallableUI",
        "MicrosoftWindows.Client.Core", "MicrosoftWindows.Client.FileExp", "MicrosoftWindows.Client.Photon", "MicrosoftWindows.Client.OOBE",
        "MicrosoftWindows.Client.LKG", "MicrosoftWindows.Client.AIX", "Microsoft.Windows.Apprep.ChxApp", "Microsoft.Windows.SecureAssessmentBrowser",
        "Microsoft.Windows.PeopleExperienceHost", "Microsoft.Windows.NarratorQuickStart", "Microsoft.Windows.ParentalControls",
        "Microsoft.Windows.XGpuEjectDialog", "Microsoft.Windows.PinningConfirmationDialog", "Microsoft.Windows.AssignedAccessLockApp",
        "Microsoft.Windows.CapturePicker", "Microsoft.Windows.PrintQueueActionCenter", "Microsoft.Windows.CallingShellApp",
        "Microsoft.CredDialogHost", "Microsoft.ECApp", "Microsoft.BioEnrollment", "Microsoft.Windows.OOBENetworkCaptivePortal",
        "Microsoft.Windows.OOBENetworkConnectionFlow", "Microsoft.AsyncTextService", "Microsoft.MicrosoftEdgeDevToolsClient",
        "Windows.CBSPreview", "windows.immersivecontrolpanel", "Windows.PrintDialog", "Microsoft.Windows.FilePicker",
        "Microsoft.Windows.AugLoop.CBS", "NcsiUwpApp", "1527c705-839a-4832-9118-54d4Bd6a0c89", "c5e2524a-ea46-4f67-841f-6a9465d9d515",
        "E2A4F912-2574-4A75-9BB0-0D023378592B", "F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE",
    };

    public static AppEntry? Find(string name) => Known.FirstOrDefault(k => string.Equals(k.Name, name, StringComparison.OrdinalIgnoreCase));
}
